package com.acma.properties;

import java.net.URISyntaxException;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.web.client.RestClientException;

import com.acma.properties.outbound.AcmaUsersOutboundApi;

@SpringBootTest
class AcmaUsermgmtServiceApplicationTests {

	@Test
	void contextLoads() {
	}

	@Autowired
	private AcmaUsersOutboundApi usersAPI;
	
	@Test
	public void testGetAllUsers() throws RestClientException, URISyntaxException {
		String accessToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5cHFuM2lZR0xDV1pKcl8yUlVpZmlqcEVzZWF3MUJBeHd5SnpqSk5neHFzIn0.eyJleHAiOjE3MjY2MjczMjcsImlhdCI6MTcyNjYyNzAyNywianRpIjoiZDhkYjMwZDctMjNlMi00YWQ3LWIxMzMtNTkzOTAyNzViODcyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL3JlYWxtcy9hY21hIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJhY2NvdW50Il0sInN1YiI6ImZlZjQxMzA5LTk4MWMtNDY1MS1hMDRjLTIxN2VlNjI5N2ZmZCIsInR5cCI6IkJlYXJlciIsImF6cCI6InN0YXRlZm9ybS1zdmMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWFjbWEiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjE5Mi4xNjguMzIuMSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1zdGF0ZWZvcm0tc3ZjIiwiY2xpZW50QWRkcmVzcyI6IjE5Mi4xNjguMzIuMSIsImNsaWVudF9pZCI6InN0YXRlZm9ybS1zdmMifQ.drAsoBLPpxMDnSnr6foCpE7JDBcUPAJhoF-G5XkAiNwvjaoMcPtewWo0p8oVf_83CDNYfK4B7vptFTRSde5_7Lu2VMlZ1ti1f1kY_WIzYUEeGe8n8SkpvyOi1pTAYVCJ5Y-hcJyE8LsYjI70HoQGuyOCGLHYaBykkm0DWs0_T7nU-GE9fM8Jd-EFekw1UTloAtZ-ao8lZlyK3xjX0rqXXIHKmedSvLZBbOBLGhTNWP3JwN2K3zGMcjjQ6wfXiVaLfEK_SLLsje06NttmloApTGJJ3Od8UyNIs0bbD7BWPjDWOK3IwE8nLdutt4ZoHAZxxdI87KjsGQkjwHFoB1McOw";
		usersAPI.getAllPropertyOwners(accessToken);
	}
}
