version: '3.8'
services:
  acma-iam-config-service: 
    container_name: acma-workforce-db
    image: mysql:latest
    restart: on-failure
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=acma-workforce
    networks:
      - acma-iam-network
    volumes:
      - E:/trainings/jrtp/ACMA/docker/acma-workforce-db:/var/lib/mysql

  acma-iam-fed-service:
    container_name: acma-customer-ldap
    image: openidentityplatform/opendj:latest
    restart: on-failure
    ports:
      - 1389:1389
      - 1636:1636
      - 4444:4444
    environment:
      - BASE_DN=dc=acma,dc=com
      - ROOT_USER_DN=uid=acmaAdmin
      - ROOT_PASSWORD=Adance123$$
    networks:
      - acma-iam-network
    volumes:
      - E:/trainings/jrtp/ACMA/docker/acma-customers-db:/opt/opendj/data
  
  acma-iam-service: 
    container_name: acma-iam
    image: quay.io/keycloak/keycloak:latest 
    command: start-dev
    restart: always
    ports:
     - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Admin123$$
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://acma-iam-config-service/acma-workforce
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    networks:
      - acma-iam-network
    depends_on:
      - acma-iam-config-service
      - acma-iam-fed-service


  acma-cache-service:
    image: redis/redis-stack:latest
    restart: on-failure    
    environment:
      REDIS_ARGS: "--requirepass password --user username on >password ~* allcommands --user default off nopass nocommands"
    ports:
      - 6379:6379
      - 8001:8001
    
    networks: 
    - acma-iam-network
  
   
  acma-cache-client-service: 
   container_name: acma-cache-client
   image: redis/redisinsight:latest
   restart: on-failure
   ports: 
    - 5053:5540
   networks: 
    - acma-iam-network

networks:
    acma-iam-network: 
      driver: bridge
    